Repository Mt-NextJs/linkle, pull requests merged in 2024-11, with the labels that each got.

#218 ✨[Feat] admin - 미리보기 모달 및 레이지 로딩 적용, 메인 페이지 #215
  src/app/admin/(block)/block-menu.tsx
  src/app/admin/(block)/calendar/components/schedule-list.tsx
  src/app/admin/(block)/divider/components/divider-preview.tsx
  src/app/admin/(block)/event/components/event-form.tsx
  src/app/admin/(block)/event/components/event-preview.tsx
  src/app/admin/(block)/image/components/image-box.tsx
  src/app/admin/(block)/image/page.tsx
  src/app/admin/components/buttons/circle-button.tsx
  src/app/admin/components/preview/components/preview-calendar.tsx
  src/app/admin/components/preview/components/preview-divider.tsx
  src/app/admin/components/preview/components/preview-event.tsx
  src/app/admin/components/preview/components/preview-image.tsx
  src/app/admin/components/preview/components/preview-link.tsx
  src/app/admin/components/preview/components/preview-text.tsx
  src/app/admin/components/preview/components/preview-video.tsx
  src/app/admin/components/preview/components/preview.tsx
  src/app/admin/components/preview/preview-modal.tsx
  src/app/admin/components/profile-box.tsx
  src/app/admin/page.tsx
  src/app/components/portal.tsx
  src/app/intro/components/basicblock.tsx
  src/app/page.tsx
Labels: ✨ Feature, ✅ Done

#223 ✨[Feat] 기존 auth token 로직 제거 #222
  .eslintrc.json
  package-lock.json
  package.json
  src/app/admin/page.tsx
  src/app/api/link/add/route.tsx
  src/app/api/link/list/route.tsx
  src/app/api/link/update/route.tsx
  src/app/api/login/route.tsx
  src/app/api/logout/route.tsx
  src/app/api/user/add/route.tsx
  src/app/api/user/delete/route.tsx
  src/app/api/user/info/route.tsx
  src/app/api/user/update/route.tsx
  src/app/intro/components/UI/empty-block.tsx
  src/app/join/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/lib/get-sequence.ts
  src/lib/mongodb.tsx
  src/utils/apis/index.ts
Labels: ♻️ Refactor, ✅ Done

#226 ✨[Feat] main 페이지, admin - 미리보기 ui 스타일 디테일 #221
  src/app/admin/(block)/block-menu.tsx
  src/app/admin/components/preview/components/preview-video.tsx
  src/app/admin/page.tsx
  src/app/page.tsx
Labels: ♻️ Refactor, ✅ Done

#225 ✨[Feat] api 변경시 몽고db update 데이터 type error 해결 #224
  src/app/api/link/add/route.tsx
Labels: ✅ Done

#229 ♻️ [Refactor] profile/detail,profile/edit api 호출부 수정 #214
  src/app/profile/detail/page.tsx
  src/app/profile/edit/page.tsx
Labels: ♻️ Refactor

#230 ✨[Feat] block list 없을 때 조건부 렌더링 처리, 메인페이지 링크 블록 타입 적용 #227
  src/app/admin/(block)/link/components/style-preview.tsx
  src/app/admin/components/preview/components/preview-link.tsx
  src/app/admin/components/preview/components/preview.tsx
  src/app/admin/components/profile-box.tsx
  src/app/admin/page.tsx
  src/app/components/page/block-list.tsx
  src/app/profile/detail/page.tsx
  src/app/profile/edit/page.tsx
Labels: ✨ Feature, ✅ Done

#234 💄[Design] admin 페이지 ui 수정 #232
  package-lock.json
  package.json
  src/app/admin/(block)/calendar/components/schedule-list.tsx
  src/app/admin/(block)/calendar/components/style-setting.tsx
  src/app/admin/(block)/paint/page.tsx
  src/app/admin/components/preview/preview-modal.tsx
  src/app/admin/page.tsx
  src/utils/apis/index.ts
Labels: ✅ Done

#236 ✨[Feat] admin 페이지 ui 수정 #232
  src/app/admin/(block)/calendar/components/schedule-form.tsx
  src/app/admin/components/home-menu.tsx
  src/app/admin/page.tsx
  src/app/intro/components/basicblock.tsx
Labels: ✅ Done

#238 🐛[Fix] 백엔드 api 1차 구축 후 점검 및 수정 #214
  src/app/admin/(block)/block-menu.tsx
  src/app/admin/(block)/calendar/components/schedule-form.tsx
  src/app/admin/(block)/calendar/components/schedule-list.tsx
  src/app/admin/(block)/calendar/manage/page.tsx
  src/app/admin/components/home-menu.tsx
  src/app/api/link/add/route.tsx
  src/app/api/link/update/route.tsx
  src/app/api/logout/route.tsx
  src/app/profile/edit/page.tsx
  src/middleware.ts
  src/types/block_types.ts
  src/utils/apis/index.ts
Labels: 🐛 Bug, ⚙️ Chore

#239 📦[Chore] 백엔드 자체 1차 구축 및 api 호출부 대거 수정, 배포 테스트
  .eslintrc.json
  package-lock.json
  package.json
  src/app/admin/(block)/block-menu.tsx
  src/app/admin/(block)/calendar/components/schedule-form.tsx
  src/app/admin/(block)/calendar/components/schedule-list.tsx
  src/app/admin/(block)/calendar/components/style-setting.tsx
  src/app/admin/(block)/calendar/manage/page.tsx
  src/app/admin/(block)/divider/components/divider-preview.tsx
  src/app/admin/(block)/event/components/event-form.tsx
  src/app/admin/(block)/event/components/event-preview.tsx
  src/app/admin/(block)/image/components/image-box.tsx
  src/app/admin/(block)/image/page.tsx
  src/app/admin/(block)/link/components/style-preview.tsx
  src/app/admin/(block)/paint/page.tsx
  src/app/admin/components/buttons/circle-button.tsx
  src/app/admin/components/home-menu.tsx
  src/app/admin/components/preview/components/preview-calendar.tsx
  src/app/admin/components/preview/components/preview-divider.tsx
  src/app/admin/components/preview/components/preview-event.tsx
  src/app/admin/components/preview/components/preview-image.tsx
  src/app/admin/components/preview/components/preview-link.tsx
  src/app/admin/components/preview/components/preview-text.tsx
  src/app/admin/components/preview/components/preview-video.tsx
  src/app/admin/components/preview/components/preview.tsx
  src/app/admin/components/preview/preview-modal.tsx
  src/app/admin/components/profile-box.tsx
  src/app/admin/page.tsx
  src/app/api/link/add/route.tsx
  src/app/api/link/delete/route.tsx
  src/app/api/link/list/route.tsx
  src/app/api/link/update/route.tsx
  src/app/api/login/route.tsx
  src/app/api/logout/route.tsx
  src/app/api/protected/route.tsx
  src/app/api/user/add/route.tsx
  src/app/api/user/delete/route.tsx
  src/app/api/user/info/route.tsx
  src/app/api/user/update/route.tsx
  src/app/components/page/block-list.tsx
  src/app/components/portal.tsx
  src/app/intro/components/UI/empty-block.tsx
  src/app/intro/components/basicblock.tsx
  src/app/join/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/profile/detail/page.tsx
  src/app/profile/edit/page.tsx
  src/lib/get-sequence.ts
  src/lib/mongodb.tsx
  src/middleware.ts
  src/types/block_types.ts
  src/utils/apis/index.ts
Labels: ⚙️ Chore

#240 🐛[Fix] 백엔드 api 1차 구축 후 배포 시도 실패, 수정 #214
  src/app/admin/(block)/calendar/components/schedule-form.tsx
  src/app/admin/(block)/link/components/link-form.tsx
  src/app/admin/(block)/paint/page.tsx
  src/app/admin/page.tsx
  src/app/profile/edit/page.tsx
  src/lib/get-cookie.ts
  src/lib/get-sequence.ts
  src/lib/post-block.ts
Labels: 🐛 Bug, ⚙️ Chore

#241 🐛[Fix] 백엔드 api 1차 구축 후 배포 시도 실패, 수정 #214
  .github/workflows/deploy.yaml
Labels: 🐛 Bug, ⚙️ Chore

#242 📦[Chore] 🐛[Fix] 백엔드 api 1차 구축 후 배포 실패 및 수정 내용 개발 브랜치 병합 #214
  .github/workflows/deploy.yaml
  src/app/admin/(block)/calendar/components/schedule-form.tsx
  src/app/admin/(block)/link/components/link-form.tsx
  src/app/admin/(block)/paint/page.tsx
  src/app/admin/page.tsx
  src/app/profile/edit/page.tsx
  src/lib/get-cookie.ts
  src/lib/get-sequence.ts
  src/lib/post-block.ts
Labels: 🐛 Bug, ⚙️ Chore

#244 ♻️[Refactor] 관리자 페이지 SEO 및 웹 접근성 최적화 #237
  src/app/admin/(block)/block-menu.tsx
  src/app/admin/components/home-menu.tsx
  src/app/admin/components/profile-box.tsx
  src/app/admin/page.tsx
Labels: 🚀 Enhancement, ♻️ Refactor, ✨ Feature

#249 🎨[Style] eslint plugin import 을 통한 프로젝트 파일 일괄 import 문 정리 #243
  .eslintrc.json
  package-lock.json
  package.json
  src/app/admin/(block)/block-menu.tsx
  src/app/admin/(block)/calendar/components/calendar-view.tsx
  src/app/admin/(block)/calendar/components/list-view.tsx
  src/app/admin/(block)/calendar/components/schedule-form.tsx
  src/app/admin/(block)/calendar/components/style-setting.tsx
  src/app/admin/(block)/calendar/manage/page.tsx
  src/app/admin/(block)/calendar/page.tsx
  src/app/admin/(block)/components/layout.tsx
  src/app/admin/(block)/divider/components/divider-preview.tsx
  src/app/admin/(block)/divider/components/divider-selector.tsx
  src/app/admin/(block)/divider/page.tsx
  src/app/admin/(block)/event/components/event-form.tsx
  src/app/admin/(block)/event/page.tsx
  src/app/admin/(block)/image/components/image-box.tsx
  src/app/admin/(block)/image/page.tsx
  src/app/admin/(block)/link/components/link-form.tsx
  src/app/admin/(block)/link/page.tsx
  src/app/admin/(block)/paint/page.tsx
  src/app/admin/(block)/text/page.tsx
  src/app/admin/(block)/video/page.tsx
  src/app/admin/components/home-menu.tsx
  src/app/admin/components/link-block.tsx
  src/app/admin/components/preview/components/preview-calendar.tsx
  src/app/admin/components/preview/components/preview-divider.tsx
  src/app/admin/components/preview/components/preview-event.tsx
  src/app/admin/components/preview/components/preview-image.tsx
  src/app/admin/components/preview/components/preview-link.tsx
  src/app/admin/components/preview/components/preview-text.tsx
  src/app/admin/components/preview/components/preview-video.tsx
  src/app/admin/components/preview/components/preview.tsx
  src/app/admin/components/preview/preview-modal.tsx
  src/app/admin/components/profile-box.tsx
  src/app/admin/page.tsx
  src/app/api/link/add/route.tsx
  src/app/api/link/delete/route.tsx
  src/app/api/link/list/route.tsx
  src/app/api/link/update/route.tsx
  src/app/api/login/route.tsx
  src/app/api/user/add/route.tsx
  src/app/api/user/delete/route.tsx
  src/app/api/user/info/route.tsx
  src/app/api/user/update/route.tsx
  src/app/components/page/block-list.tsx
  src/app/intro/components/basicblock.tsx
  src/app/intro/page.tsx
  src/app/join/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/profile/detail/page.tsx
  src/app/profile/edit/page.tsx
  src/components/common/ui/theme-toggle.tsx
  src/types/block_types.ts
  src/utils/with-login.tsx
Labels: 🚀 Enhancement, 🛠 Tooling, ♻️ Refactor

#256 ✨ [Feat] 링크 블록 SEO 최적화 #255
  src/app/admin/(block)/components/layout.tsx
  src/app/admin/(block)/link/components/link-form.tsx
  src/app/admin/(block)/link/components/style-preview.tsx
  src/app/admin/(block)/link/components/style-type.tsx
  src/app/admin/components/admin-manu.tsx
  src/app/admin/components/block-list-section.tsx
  src/app/admin/components/link-block.tsx
  src/app/admin/components/video-block.tsx
  src/app/admin/components/visit-section.tsx
  src/app/admin/page.tsx
  src/app/components/page/block-list.tsx
  src/app/intro/components/basicblock.tsx
  src/types/apis.ts
Labels: ♻️ Refactor, 🚧 In Progress

#259 ✨[Feat] 캘린더 블록 순서 변경 api 추가 #258
  src/app/admin/page.tsx
  src/app/components/circle-button-box.tsx
  src/utils/apis/index.ts
Labels: ✨ Feature, ✅ Done

#261 💄[Design] 개별 페이지 다크모드 조정 작업, 중간 병합 #216
  package-lock.json
  package.json
  public/assets/icons/theme/dark/icon_back.svg
  public/assets/icons/theme/dark/icon_close.svg
  src/app/admin/components/profile-box.tsx
  src/app/intro/page.tsx
  src/components/common/ui/theme-toggle.tsx
  src/styles/common.css
  src/styles/global.css
  tailwind.config.ts
Labels: ♻️ Refactor, 🚧 In Progress, 🎨 Design

#263 🐛[Fix] 다크모드 깜빡임 이슈 #252
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/ui/theme-toggle.tsx
Labels: 🐛 Bug, ✅ Done

#267 [Feat] 블록 미리보기 모달 이슈, 캘린더 블록 접근 로직, zod 적용
  src/app/admin/(block)/block-menu.tsx
  src/app/admin/components/block-list-section.tsx
  src/app/admin/components/profile-box.tsx
  src/app/components/page/block-list.tsx
  src/types/block_types.ts
  src/utils/apis/index.ts
Labels: ✨ Feature, ✅ Done

#269 🐛[Fix] 이슈, 브랜치 정리 전, 병합 에러 해결 #216
  src/app/admin/components/block-list-section.tsx
  src/app/admin/components/preview/components/preview-calendar.tsx
  src/app/admin/components/preview/components/preview-divider.tsx
  src/app/admin/components/preview/components/preview-event.tsx
  src/app/admin/components/preview/components/preview-image.tsx
  src/app/admin/components/preview/components/preview-link.tsx
  src/app/admin/components/preview/components/preview-text.tsx
  src/app/admin/components/preview/components/preview-video.tsx
  src/app/admin/components/preview/preview-modal.tsx
  src/app/api/link/callendar/update/route.tsx
  src/app/layout.tsx
Labels: 🐛 Bug, ⚙️ Chore, 🚀 Enhancement, ♻️ Refactor, 🎨 Design

#272 ✨ [Feat] calendar api 일부 구현 #214
  src/app/api/link/calendar/add/route.tsx
Labels: ✨ Feature

#276 ✨[Feat] 스케줄 추가 api 로직 변경 #273
  src/app/admin/(block)/calendar/components/schedule-form.tsx
  src/app/admin/(block)/calendar/components/schedule-list.tsx
  src/app/admin/(block)/calendar/components/style-setting.tsx
  src/app/admin/(block)/calendar/components/types.ts
  src/app/admin/(block)/calendar/page.tsx
  src/app/admin/(block)/divider/page.tsx
  src/app/admin/(block)/event/components/event-form.tsx
  src/app/admin/(block)/image/page.tsx
  src/app/admin/(block)/link/components/link-form.tsx
  src/app/admin/(block)/text/page.tsx
  src/app/admin/(block)/video/page.tsx
  src/app/login/page.tsx
  src/types/apis.ts
  src/types/user.ts
  src/utils/apis/index.ts
Labels: ✨ Feature, ✅ Done

#278 💄[Design] 인트로, 로그인, 회원가입, 회원정보 조회 / 수정 페이지 레이아웃 완성 #270
  src/app/admin/(block)/components/form-input.tsx
  src/app/intro/page.tsx
  src/app/join/page.tsx
  src/app/login/page.tsx
  src/app/profile/detail/page.tsx
  src/app/profile/edit/page.tsx
  src/components/providers/theme-provider.tsx
  src/styles/global.css
Labels: 🚀 Enhancement, 🎨 Design

#279 ✨[Feat] 스케줄 추가 api 로직 변경 #273
  src/app/admin/(block)/calendar/components/list-view.tsx
  src/app/admin/(block)/calendar/components/schedule-list.tsx
  src/app/admin/(block)/calendar/components/style-setting.tsx
  src/app/admin/(block)/calendar/page.tsx
  src/app/admin/components/preview/components/preview-calendar.tsx
Labels: ♻️ Refactor, ✅ Done

#280 ✨ [Feat] 동적 api 일부 구현 #214
  src/app/api/link/list/[id]/route.tsx
Labels: ✨ Feature

#283 ✨[Feat] main -> profile/[userId] , intro -> main 페이지 이동 및 profile api…
  src/app/admin/(block)/image/components/image-box.tsx
  src/app/admin/components/block-list-section.tsx
  src/app/admin/layout.tsx
  src/app/components/page/block-list.tsx
  src/app/intro/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/profile/[userId]/page.tsx
  src/components/UI/empty-block.tsx
  src/components/UI/toggle-button.tsx
  src/components/basicblock.tsx
  src/components/error-boundary.tsx
  src/components/navigation.tsx
  src/utils/apis/index.ts
Labels: ✨ Feature, ✅ Done

#285 [Feat] calendar api 마무리
  src/app/api/link/calendar/update/route.tsx
  src/app/api/link/update/route.tsx
Labels: ✨ Feature

#287 [Feat] login api 수정
  src/app/api/login/route.tsx
Labels: ✨ Feature

#288 💄[Design] 메인 페이지 디자인(레이아웃) 조정 중간 병합 #281
  src/app/admin/(block)/components/contour.tsx
  src/app/admin/(block)/link/components/style-preview.tsx
  src/app/admin/components/admin-menu.tsx
  src/app/admin/components/buttons/circle-button.tsx
  src/app/admin/components/home-menu.tsx
  src/app/admin/components/preview/components/preview-divider.tsx
  src/app/admin/components/preview/components/preview-event.tsx
  src/app/admin/components/preview/components/preview-image.tsx
  src/app/admin/components/preview/components/preview-link.tsx
  src/app/admin/components/preview/components/preview-text.tsx
  src/app/admin/components/preview/components/preview-video.tsx
  src/app/admin/components/preview/components/preview.tsx
  src/app/admin/components/profile-box.tsx
  src/app/admin/page.tsx
  src/app/components/page/block-list.tsx
  src/app/profile/[userId]/page.tsx
  src/components/common/ui/theme-toggle.tsx
Labels: 🚀 Enhancement, 🎨 Design

#291 [Feat] userlist api 구현
  src/app/api/user/userlist/route.tsx
Labels: ✨ Feature

#293 ✨[Feat] home 페이지 작성 #292
  .github/workflows/deploy.yaml
  public/assets/images/main-default.jpg
  src/app/home/page.tsx
  src/middleware.ts
  src/utils/apis/index.ts
  src/utils/kakao-script.tsx
Labels: 🚧 In Progress, ✨ Feature

#294 ✨[Feat] home 페이지 작성 #292
  public/assets/images/placeholder.svg
  src/app/admin/components/preview/components/preview.tsx
  src/app/components/page/block-list.tsx
  src/app/home/components/header.tsx
  src/app/home/components/post-card.tsx
  src/app/home/page.tsx
Labels: ✨ Feature, ✅ Done

#295 ✨ [Feat] api 수정 #214
  src/app/api/link/list/[id]/route.tsx
Labels: ✨ Feature

#296 💄[Design] 메인 페이지 레아이웃 조정 마무리 #281
  src/app/admin/(block)/image/components/image-box.tsx
  src/app/admin/(block)/image/page.tsx
  src/components/UI/empty-block.tsx
  src/styles/global.css
Labels: 🚀 Enhancement, 🎨 Design

#298 ✨[Feat] 블록 삭제, profile 메뉴, home ui 수정 #297
  src/app/admin/components/block-list-section.tsx
  src/app/admin/components/home-menu.tsx
  src/app/admin/components/profile-box.tsx
  src/app/admin/components/user-menu.tsx
  src/app/home/components/header.tsx
  src/components/basicblock.tsx
  src/config/route.tsx
  src/config/types.tsx
Labels: ✨ Feature, ✅ Done

#301 ✨ [24.11.27] admin 페이지 레아이웃(스타일) 조정 #299
  components.json
  package-lock.json
  package.json
  src/app/admin/(block)/block-menu.tsx
  src/app/admin/(block)/calendar/components/calendar-view.tsx
  src/app/admin/(block)/calendar/components/schedule-list.tsx
  src/app/admin/(block)/calendar/components/style-setting.tsx
  src/app/admin/(block)/calendar/page.tsx
  src/app/admin/components/admin-menu.tsx
  src/app/admin/components/block-list-section.tsx
  src/app/admin/components/calendar-block.tsx
  src/app/admin/components/divide-block-sub/dot.tsx
  src/app/admin/components/divide-block-sub/line.tsx
  src/app/admin/components/divide-block-sub/point.tsx
  src/app/admin/components/divide-block-sub/zigzag.tsx
  src/app/admin/components/divide-block.tsx
  src/app/admin/components/event-block.tsx
  src/app/admin/components/home-menu.tsx
  src/app/admin/components/image-block.tsx
  src/app/admin/components/link-block-sub/type-four.tsx
  src/app/admin/components/link-block-sub/type-one.tsx
  src/app/admin/components/link-block-sub/type-three.tsx
  src/app/admin/components/link-block-sub/type-two.tsx
  src/app/admin/components/link-block.tsx
  src/app/admin/components/preview/components/preview.tsx
  src/app/admin/components/profile-box.tsx
  src/app/admin/components/text-block.tsx
  src/app/admin/components/user-menu.tsx
  src/app/admin/components/video-block.tsx
  src/app/admin/page.tsx
  src/app/home/components/header.tsx
  src/app/home/components/post-card.tsx
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/profile/[userId]/components/icons.tsx
  src/app/profile/[userId]/page.tsx
  src/components/UI/button.tsx
  src/components/UI/card.tsx
  src/components/UI/scroll-area.tsx
  src/components/UI/separator.tsx
  src/components/UI/switch.tsx
  src/components/basicblock.tsx
  src/components/common/ui/theme-toggle.tsx
  src/lib/utils.ts
  src/styles/common.css
  src/styles/global.css
  src/types/block_types.ts
  src/utils/with-login.tsx
  tailwind.config.ts
  tsconfig.json
Labels: 🚧 In Progress, ✨ Feature
