Repository Mt-NextJs/linkle, pull requests merged in 2024-10, with the labels that each got.

#43 📦[Chore] default 브랜치 변경 후 main의 내용들 develop 브랜치 반영을 위한 작업 #1
  api.txt
  src/app/admin/page.tsx
  src/app/login/page.tsx
Labels: ⚙️ Chore, 🔥 High Priority

#42 📦[Chore] 프로젝트 사전 배포 작업 진행 #5
  .env
  .eslintrc.json
  .github/workflows/deploy.yaml
  .gitignore
  api.txt
  build.sh
  package-lock.json
  package.json
  public/assets/icons/item_card_002.png
  public/assets/icons/item_card_004.png
  src/app/(intro)/components/navigation.tsx
  src/app/admin/layout.tsx
  src/app/link/page.tsx
Labels: ⚙️ Chore, 🚧 In Progress, 🔍 Needs Review, 🔥 High Priority

#44 📦[Chore] 사전 배포를 위한 작업 진행중 #5
  .env
  .eslintrc.json
  .github/workflows/deploy.yaml
  .gitignore
  api.txt
  build.sh
  package-lock.json
  package.json
  public/assets/icons/item_card_002.png
  public/assets/icons/item_card_004.png
  src/app/(intro)/components/navigation.tsx
  src/app/admin/layout.tsx
  src/app/link/page.tsx
Labels: ⚙️ Chore, 🚧 In Progress, 🔥 High Priority

#45 📦[Chore] github action 실행 중 node 관련 문제 발견, 수정 #5
  .github/workflows/deploy.yaml
Labels: 🐛 Bug, ⚙️ Chore, 🚧 In Progress, 🔥 High Priority

#46 📦[Chore] github action 실행 중 node 관련 문제 발견, 수정 #5
  .github/workflows/deploy.yaml
Labels: 🐛 Bug, ⚙️ Chore, 🚧 In Progress, 🔥 High Priority

#50 📦[Chore] github action 실행 중 에러 발견, 점검 중 stylelint 관련 수정 내용 반영 및 container 제거 #5
  .github/workflows/deploy.yaml
  package.json
Labels: 🐛 Bug

#77 📦[Chore] 프로젝트 세팅 및 빌딩 마무리 #1
  .gitignore
  README.md
  api.txt
Labels: 📄 Docs, ⚙️ Chore, ✨ Feature, ✅ Done

#78 ✨[Feat] 구분선 블록 퍼블리싱 및 API 연동
  public/assets/images/divider_preview_image.png
  src/app/admin/block/divider/components/divider-preview.tsx
  src/app/admin/block/divider/components/divider-selector.tsx
  src/app/admin/block/divider/page.tsx
  src/app/admin/block/divider/types.ts
Labels: 🎨 Design, ✨ Feature

#79 ✨[Feat] 링크 블록 URL 유효성 검사 및 디자인 수정
  src/app/admin/block/link/components/form-input.tsx
  src/app/admin/block/link/components/link-form.tsx
  src/app/admin/block/link/components/style-preview.tsx
  src/app/admin/block/link/components/style-type.tsx
  src/app/admin/block/link/page.tsx
Labels: 🎨 Design, ✨ Feature

#82 ✨[Feat] 이벤트 블록 퍼블리싱 및 일부 기능 구현
  package-lock.json
  package.json
  src/app/admin/block/event/components/calendar.tsx
  src/app/admin/block/event/components/event-form-input.tsx
  src/app/admin/block/event/components/event-form.tsx
  src/app/admin/block/event/components/event-preview.tsx
  src/app/admin/block/event/page.tsx
Labels: 🎨 Design, ✨ Feature

#83 ✨[Feat] 비로그인 상태에서의 사용자 랜딩페이지 이동을 위한 미들웨어 파일 구축 및 로그인 로직 점검 #74
  src/app/page.tsx
  src/middleware.ts
Labels: 🚀 Enhancement, 🚧 In Progress, ✨ Feature

#93 ✨[Feat] 중간 병합 후 배포 테스트를 위한 커밋 #91
  src/app/admin/layout.tsx
  src/app/page.tsx
  src/middleware.ts
Labels: ⚙️ Chore, 🚧 In Progress, 🔥 High Priority

#100 ✨ admin 페이지, block-image, block-video api 연동 #87
  src/app/(intro)/components/basicblock.tsx
  src/app/admin/block/components/layout.tsx
  src/app/admin/block/divider/page.tsx
  src/app/admin/block/image/components/image-box.tsx
  src/app/admin/block/image/page.tsx
  src/app/admin/block/video/page.tsx
  src/app/admin/page.tsx
  src/app/components/buttons/add-button.tsx
  src/app/components/buttons/button-box.tsx
  src/app/components/text-input-box.tsx
Labels: ✨ Feature, ✅ Done

#105 ✨[Feat] block 공통 컴포넌트 작성 - input, button, layout #104
  src/app/admin/block/components/buttons/add-button.tsx
  src/app/admin/block/components/buttons/button-box.tsx
  src/app/admin/block/components/form-input.tsx
  src/app/admin/block/components/layout.tsx
  src/app/admin/block/components/text-input-box.tsx
  src/app/admin/block/divider/page.tsx
  src/app/admin/block/image/page.tsx
  src/app/admin/block/link/components/form-input.tsx
  src/app/admin/block/link/components/link-form.tsx
  src/app/admin/block/link/page.tsx
  src/app/admin/block/video/page.tsx
  src/app/admin/page.tsx
  src/app/components/buttons/add-button.tsx
  src/lib/check-url.ts
Labels: ♻️ Refactor, ✅ Done

#106 ✨[Feat] block - layout 컴포넌트 css 수정 #94
  src/styles/global.css
Labels: ✨ Feature, ✅ Done

#108 ✨[Feat] 이미지, 동영상 박스 css 변경, 각 url 유효성 검사 #88
  .env
  src/app/admin/block/image/components/image-box.tsx
  src/app/admin/block/image/page.tsx
  src/app/admin/block/video/page.tsx
Labels: ✨ Feature, ✅ Done

#113 ✨[Feat] block layout 물음표 아이콘을 컴포넌트로 분리 #110
  src/app/admin/block/components/question-icon.tsx
Labels: ✨ Feature, ✅ Done

#116 ✨[Feat] block 생성 api 호출하는 함수 생성 #111
  src/app/admin/block/components/layout.tsx
  src/app/admin/block/image/components/image-box.tsx
  src/app/admin/block/image/page.tsx
  src/app/admin/block/video/page.tsx
  src/lib/post-block.ts
Labels: ✨ Feature, ✅ Done

#117 ✨[Feat] 이벤트 블록 API 연결 및 디자인 수정 #109
  .env
  src/app/admin/block/event/components/calendar.tsx
  src/app/admin/block/event/components/event-form-input.tsx
  src/app/admin/block/event/components/event-form.tsx
  src/app/admin/block/event/page.tsx
Labels: 🎨 Design, ✨ Feature

#112 ✨[Feat] 랜딩 페이지 구현 #32
  .env
  src/app/(intro)/page.tsx
  src/app/admin/block/image/components/image-box.tsx
  src/app/admin/block/image/page.tsx
  src/app/admin/layout.tsx
  src/app/admin/page.tsx
  src/app/intro/components/UI/empty-block.tsx
  src/app/intro/components/UI/toggle-button.tsx
  src/app/intro/components/basicblock.tsx
  src/app/intro/components/error-boundary.tsx
  src/app/intro/components/navigation.tsx
  src/app/intro/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/config/route.tsx
  src/middleware.ts
Labels: 🚧 In Progress, 🎨 Design, ✨ Feature

#118 🎨✨ [Style/Feat] 링크 블록 UI 수정 및 기능 추가 #97
  src/app/admin/block/components/buttons/add-button.tsx
  src/app/admin/block/link/components/link-form.tsx
  src/app/admin/block/link/components/style-preview.tsx
  src/app/link/page.tsx
Labels: 🎨 Design, ✨ Feature

#121 🐛[Fix] develop to main 병합 과정에서의 충돌 해결을 위한 PR #119
  .env
  src/app/(intro)/page.tsx
  src/app/admin/block/components/buttons/add-button.tsx
  src/app/admin/block/components/form-input.tsx
  src/app/admin/block/components/layout.tsx
  src/app/admin/block/components/question-icon.tsx
  src/app/admin/block/components/text-input-box.tsx
  src/app/admin/block/event/components/calendar.tsx
  src/app/admin/block/event/components/event-form.tsx
  src/app/admin/block/event/page.tsx
  src/app/admin/block/image/components/image-box.tsx
  src/app/admin/block/image/page.tsx
  src/app/admin/block/link/components/link-form.tsx
  src/app/admin/block/link/components/style-preview.tsx
  src/app/admin/block/link/page.tsx
  src/app/admin/block/video/page.tsx
  src/app/admin/components/calendar-block.tsx
  src/app/admin/components/divide-block.tsx
  src/app/admin/components/event-block.tsx
  src/app/admin/components/link-block-sub/type-two.tsx
  src/app/admin/components/video-block.tsx
  src/app/admin/layout.tsx
  src/app/admin/page.tsx
  src/app/intro/components/UI/empty-block.tsx
  src/app/intro/components/UI/toggle-button.tsx
  src/app/intro/components/basicblock.tsx
  src/app/intro/components/error-boundary.tsx
  src/app/intro/components/navigation.tsx
  src/app/intro/page.tsx
  src/app/layout.tsx
  src/app/link/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/config/route.tsx
  src/lib/check-url.ts
  src/lib/post-block.ts
  src/middleware.ts
  src/styles/global.css
Labels: 🐛 Bug, ⚙️ Chore, 🚧 In Progress, 🔥 High Priority

#123 ✨[Feat] question-icon.tsx 아이콘 hover 영역 조정 #122
  src/app/admin/block/components/question-icon.tsx
  tailwind.config.ts
Labels: 🐛 Bug, ✅ Done

#126 🐛[Fix] develop to main 병합 과정에서의 충돌 해결을 위한 PR #119
  src/app/admin/block/event/components/event-form-input.tsx
  src/app/admin/block/link/components/form-input.tsx
Labels: 🐛 Bug, ⚙️ Chore, 🚧 In Progress, 🔥 High Priority

#119 📦[Chore] 10.22(화) 중간 발표 전 작업물 병합 및 배포 테스트
  public/assets/icons/index.ts
  src/app/admin/(block)/block-menu.tsx
  src/app/admin/(block)/calendar/add/page.tsx
  src/app/admin/(block)/calendar/components/add-schedule-form.tsx
  src/app/admin/(block)/calendar/components/calendar-header.tsx
  src/app/admin/(block)/calendar/components/calendar-view.tsx
  src/app/admin/(block)/calendar/components/list-view.tsx
  src/app/admin/(block)/calendar/components/schedule-list.tsx
  src/app/admin/(block)/calendar/components/style-setting.tsx
  src/app/admin/(block)/calendar/page.tsx
  src/app/admin/(block)/components/buttons/add-button.tsx
  src/app/admin/(block)/components/buttons/button-box.tsx
  src/app/admin/(block)/components/contour.tsx
  src/app/admin/(block)/components/form-input.tsx
  src/app/admin/(block)/components/layout.tsx
  src/app/admin/(block)/components/question-icon.tsx
  src/app/admin/(block)/components/text-input-box.tsx
  src/app/admin/(block)/divider/components/divider-preview.tsx
  src/app/admin/(block)/divider/components/divider-selector.tsx
  src/app/admin/(block)/divider/page.tsx
  src/app/admin/(block)/divider/types.ts
  src/app/admin/(block)/event/components/calendar.tsx
  src/app/admin/(block)/event/components/event-form.tsx
  src/app/admin/(block)/event/components/event-preview.tsx
  src/app/admin/(block)/event/page.tsx
  src/app/admin/(block)/image/components/image-box.tsx
  src/app/admin/(block)/image/page.tsx
  src/app/admin/(block)/link/components/link-form.tsx
  src/app/admin/(block)/link/components/style-preview.tsx
  src/app/admin/(block)/link/components/style-type.tsx
  src/app/admin/(block)/link/page.tsx
  src/app/admin/(block)/video/page.tsx
  src/app/admin/block/page.tsx
  src/app/admin/page.tsx
  src/app/components/Portal.tsx
  src/app/layout.tsx
  src/config/block_types.ts
  src/lib/post-block.ts
  tailwind.config.ts
Labels: ⚙️ Chore, 🚧 In Progress, 🔥 High Priority

#128 🚑[HOTFIX] dev to main 브랜치 병합 이후 자동화 액션 실패, 보호 해제 후 관련 설정 점검 #119
  src/app/admin/block/calendar/add/page.tsx
  src/app/admin/block/calendar/components/add-schedule-form.tsx
  src/app/admin/block/calendar/components/calendar-header.tsx
  src/app/admin/block/calendar/components/calendar-view.tsx
  src/app/admin/block/calendar/components/list-view.tsx
  src/app/admin/block/calendar/components/schedule-list.tsx
  src/app/admin/block/calendar/components/style-setting.tsx
  src/app/admin/block/calendar/page.tsx
  src/app/admin/block/divider/components/divider-preview.tsx
  src/app/admin/block/divider/components/divider-selector.tsx
  src/app/admin/block/divider/page.tsx
  src/app/admin/block/divider/types.ts
  src/app/admin/block/event/components/calendar.tsx
  src/app/admin/block/event/components/event-form-input.tsx
  src/app/admin/block/event/components/event-form.tsx
  src/app/admin/block/event/components/event-preview.tsx
  src/app/admin/block/event/page.tsx
  src/app/admin/block/link/components/form-input.tsx
  src/app/admin/block/link/components/link-form.tsx
  src/app/admin/block/link/components/style-preview.tsx
  src/app/admin/block/link/components/style-type.tsx
  src/app/admin/block/link/page.tsx
Labels: 🐛 Bug, ⚙️ Chore, ✅ Done, 🔥 High Priority

#129 ✨[Feat] 캘린더 블록 API (추가, 수정, 삭제) 연동 및 기능 개선
  package-lock.json
  package.json
  src/app/admin/(block)/calendar/add/page.tsx
  src/app/admin/(block)/calendar/components/calendar-header.tsx
  src/app/admin/(block)/calendar/components/calendar-view.tsx
  src/app/admin/(block)/calendar/components/schedule-form.tsx
  src/app/admin/(block)/calendar/components/schedule-list.tsx
  src/app/admin/(block)/calendar/manage/page.tsx
Labels: 🎨 Design, ✨ Feature

#131 ✨[Feat] 블록 선택하기 모달 배경 opacity 적용 및 구분선 링크 클릭 시 주소 변경 #130
  src/app/admin/(block)/block-menu.tsx
  src/app/admin/page.tsx
  src/config/block_types.ts
Labels: ✨ Feature, ✅ Done

#133 ✨[Feat] 이벤트 블록 더보기(화살표) 기능 구현 #109
  package-lock.json
  package.json
  src/app/admin/(block)/event/components/calendar.tsx
  src/app/admin/(block)/event/components/event-form.tsx
  src/app/admin/(block)/event/components/event-preview.tsx
  src/app/admin/(block)/event/page.tsx
Labels: 🚧 In Progress, ✨ Feature

#132 ✨[Feat] 사용자 일정 리스트뷰 및 캘린더뷰 표시 기능 추가 #101
  src/app/admin/(block)/calendar/components/calendar-view.tsx
  src/app/admin/(block)/calendar/components/list-view.tsx
  src/app/admin/(block)/calendar/components/schedule-list.tsx
  src/app/admin/(block)/calendar/components/style-setting.tsx
  src/app/admin/(block)/calendar/components/types.ts
Labels: ✨ Feature

#135 🐛[Fix] 구분선 선택 기능 오작동 수정 #134
  src/app/admin/(block)/divider/components/divider-selector.tsx
Labels: 🐛 Bug

#136 📦[Chore] 중간 발표전 배포를 위한 PR 작성
  package-lock.json
  package.json
  src/app/admin/(block)/block-menu.tsx
  src/app/admin/(block)/calendar/add/page.tsx
  src/app/admin/(block)/calendar/components/calendar-header.tsx
  src/app/admin/(block)/calendar/components/calendar-view.tsx
  src/app/admin/(block)/calendar/components/list-view.tsx
  src/app/admin/(block)/calendar/components/schedule-form.tsx
  src/app/admin/(block)/calendar/components/schedule-list.tsx
  src/app/admin/(block)/calendar/components/style-setting.tsx
  src/app/admin/(block)/calendar/components/types.ts
  src/app/admin/(block)/calendar/manage/page.tsx
  src/app/admin/(block)/divider/components/divider-selector.tsx
  src/app/admin/(block)/event/components/calendar.tsx
  src/app/admin/(block)/event/components/event-form.tsx
  src/app/admin/(block)/event/components/event-preview.tsx
  src/app/admin/(block)/event/page.tsx
  src/app/admin/page.tsx
  src/config/block_types.ts
Labels: ⚙️ Chore

#144 🐛[Fix] 이벤트 블록 더보기 버튼 상태 유지 문제 해결 #115
  src/app/admin/(block)/calendar/manage/page.tsx
  src/app/admin/(block)/event/components/event-preview.tsx
Labels: 🐛 Bug, ✅ Done

#145 📦[Chore] 중간 발표전 배포를 위한 PR 작성 #136
  package-lock.json
  src/app/admin/(block)/components/question-icon.tsx
  src/app/admin/(block)/event/components/event-preview.tsx
  src/app/admin/(block)/image/page.tsx
  src/app/admin/(block)/text/page.tsx
  src/app/admin/(block)/video/page.tsx
  src/app/admin/components/divide-block-sub/dot.tsx
  src/app/admin/components/divide-block-sub/gap.tsx
  src/app/admin/components/divide-block-sub/line.tsx
  src/app/admin/components/divide-block-sub/point.tsx
  src/app/admin/components/divide-block-sub/zigzag.tsx
  src/app/admin/components/divide-block.tsx
  src/app/admin/components/image-block.tsx
  src/app/admin/components/text-block.tsx
  src/app/admin/page.tsx
  src/app/intro/components/basicblock.tsx
  src/config/block_types.ts
Labels: ⚙️ Chore, ✅ Done, 🔥 High Priority

#156 💄[Design] 로그인 페이지 퍼블리싱 및 기능 추가 #74
  src/app/login/page.tsx
  src/middleware.ts
Labels: 🎨 Design, ✨ Feature

#160 ✨[Feat] 구분선 블록 한글 키 값을 영어로 변경 #159
  src/app/admin/(block)/divider/components/divider-preview.tsx
  src/app/admin/(block)/divider/components/divider-selector.tsx
  src/app/admin/(block)/divider/page.tsx
  src/app/admin/(block)/divider/types.ts
Labels: 🎨 Design, ✨ Feature

#158 💄[Design] 캘린더 블록 UI 개선 #148
  package-lock.json
  package.json
  src/app/admin/(block)/calendar/components/calendar-header.tsx
  src/app/admin/(block)/calendar/components/calendar-view.tsx
  src/app/admin/(block)/calendar/components/date-time-input.tsx
  src/app/admin/(block)/calendar/components/list-view.tsx
  src/app/admin/(block)/calendar/components/schedule-form.tsx
  src/app/admin/(block)/calendar/components/schedule-list.tsx
  src/app/admin/(block)/calendar/components/style-setting.tsx
  src/app/admin/(block)/calendar/manage/page.tsx
  src/app/admin/(block)/calendar/page.tsx
Labels: 🎨 Design, ✨ Feature

#162 ✨[Feat] 회원가입 페이지 퍼블리싱 및 기능 구현 #34
  src/app/join/components/animated-text.tsx
  src/app/join/page.tsx
  tailwind.config.ts
Labels: 🎨 Design, ✨ Feature, ✅ Done

#165 ✨[Feat] 이벤트 블록 UI 수정 및 기능 개선 #146
  package-lock.json
  src/app/admin/(block)/event/components/calendar.tsx
  src/app/admin/(block)/event/components/event-date-picker.tsx
  src/app/admin/(block)/event/components/event-form.tsx
  src/app/admin/(block)/event/components/event-preview.tsx
  src/styles/datepicker-custom.css
  src/styles/global.css
Labels: ✨ Feature

#171 💄[Design] 아이콘 등 필요 비주얼 요소 추가 작업 #166
  public/assets/icons/SVG/icon/icon_calendar.svg
  public/assets/icons/SVG/icon/icon_divider.svg
  public/assets/icons/SVG/icon/icon_event.svg
  public/assets/icons/SVG/icon/icon_image.svg
  public/assets/icons/SVG/icon/icon_link.svg
  public/assets/icons/SVG/icon/icon_text.svg
  public/assets/icons/SVG/icon/icon_video.svg
  public/assets/icons/SVG/item/item_dashed.svg
  public/assets/icons/SVG/item/item_dotted.svg
  public/assets/icons/SVG/item/item_line.svg
  public/assets/icons/SVG/item/item_zigzag.svg
Labels: ⚙️ Chore, 🎨 Design

#174 🐛[Fix] date-fns locale 모듈 임포트 오류 수정 #173
  package-lock.json
  src/app/admin/(block)/event/components/event-date-picker.tsx
Labels: 🐛 Bug, ⚙️ Chore

#179 ✨[Feat] 회원 정보 조회 및 수정 페이지 퍼블리싱 및 구현 #163
  src/app/admin/components/home-menu.tsx
  src/app/join/page.tsx
  src/app/profile/[id]/detail/page.tsx
  src/app/profile/[id]/edit/page.tsx
  src/app/profile/detail/page.tsx
  src/app/profile/edit/page.tsx
  src/components/common/ui/animated-text.tsx
  src/lib/get-cookie.ts
  src/middleware.ts
  src/types/user.ts
  tsconfig.json
Labels: 🎨 Design, ✨ Feature

#193 🐛[Fix] api utils #190
  src/utils/apis/index.ts
Labels: 🐛 Bug, ✅ Done

#191 💄[Design] 캘린더 블록 UI/UX 개선 #188
  src/app/admin/(block)/calendar/components/calendar-view.tsx
  src/app/admin/(block)/calendar/components/date-time-input.tsx
  src/app/admin/(block)/calendar/components/list-view.tsx
  src/app/admin/(block)/calendar/components/schedule-list.tsx
  src/app/admin/(block)/calendar/components/style-setting.tsx
  tailwind.config.ts
Labels: 🎨 Design

#199 💄[Design] 작업영역 style 단일화 (color 및 코드 스타일) #198
  src/app/admin/(block)/block-menu.tsx
  src/app/admin/(block)/components/buttons/add-button.tsx
  src/app/admin/(block)/components/contour.tsx
  src/app/admin/(block)/components/form-input.tsx
  src/app/admin/(block)/components/question-icon.tsx
  src/app/admin/(block)/components/text-input-box.tsx
  src/app/admin/(block)/image/components/image-box.tsx
  src/app/admin/(block)/video/page.tsx
  src/styles/global.css
  tailwind.config.ts
Labels: 🎨 Design, ✅ Done

#201 🐛[Fix] image url 확장자 검사 로직 제거 #200
  src/app/admin/(block)/image/page.tsx
  src/lib/check-url.ts
Labels: 🐛 Bug, ✅ Done

#197 🐛[Fix] 캘린더 일정 시간 및 날짜 표시 오류 수정 #192
  src/app/admin/(block)/calendar/components/date-time-input.tsx
  src/app/admin/(block)/calendar/components/list-view.tsx
  src/app/admin/(block)/calendar/components/schedule-form.tsx
  src/app/admin/(block)/calendar/components/schedule-list.tsx
Labels: 🐛 Bug

#203 🐛[Fix] 이미지 URL 유효성 검사 시 CORS 및 불필요한 네트워크 요청 문제 #107
  src/app/admin/(block)/components/layout.tsx
  src/app/admin/(block)/link/components/link-form.tsx
  src/app/admin/(block)/link/components/style-preview.tsx
  src/app/admin/(block)/link/components/style-type.tsx
Labels: 🐛 Bug, ❌ Closed

#205 💄[Design] 다크모드 전환 기능 및 테마 설정 #180
  .husky/verifyCommitMessage.js
  src/app/admin/(block)/divider/components/divider-preview.tsx
  src/app/admin/components/home-menu.tsx
  src/app/admin/page.tsx
  src/app/join/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/components/common/ui/theme-toggle.tsx
  src/components/providers/theme-provider.tsx
  src/config/route.tsx
  src/config/types.tsx
  src/styles/common.css
  src/styles/global.css
  tailwind.config.ts
Labels: 🚀 Enhancement, 🚧 In Progress, 🎨 Design, ✨ Feature

#202 ✨ [Feat] basicblock하부컴포넌트(구분선) 이미지 적용 #14
  src/app/admin/components/divide-block-sub/dot.tsx
  src/app/admin/components/divide-block-sub/gap.tsx
  src/app/admin/components/divide-block-sub/line.tsx
  src/app/admin/components/divide-block-sub/point.tsx
  src/app/admin/components/divide-block-sub/zigzag.tsx
  src/app/admin/components/video-block.tsx
  src/components/sections/admin/sample.tsx
Labels: ✨ Feature

#207 🐛[Fix] getSequence 타입 에러 방지 위한 기본값 설정 #206
  src/app/admin/(block)/calendar/components/schedule-form.tsx
Labels: 🐛 Bug

#212 🐛[Fix] useSearchParams() 사용 영역 Suspense 적용 #211
  src/app/admin/(block)/block-menu.tsx
  src/app/admin/(block)/calendar/components/schedule-list.tsx
  src/app/admin/(block)/calendar/page.tsx
  src/app/admin/(block)/components/layout.tsx
  src/app/admin/(block)/divider/page.tsx
  src/app/admin/(block)/event/page.tsx
  src/app/admin/(block)/image/page.tsx
  src/app/admin/(block)/link/page.tsx
  src/app/admin/(block)/text/page.tsx
  src/app/admin/(block)/video/page.tsx
  src/app/intro/page.tsx
  src/app/join/components/animated-text.tsx
  src/components/sections/admin/sample.tsx
  src/lib/check-url.ts
Labels: 🐛 Bug, ✅ Done
